// const companyConstant = {
//     GET_COMPANIES_START: "GET_COMPANIES_START",
//     GET_COMPANIES_SUCCESS: "GET_COMPANIES_SUCCESS",
//     GET_COMPANIES_FAILURE: "GET_COMPANIES_FAILURE",
//     READ_COMPANY_START: "READ_COMPANY_START",
//     READ_COMPANY_SUCCESS: "READ_COMPANY_SUCCESS",
//     READ_COMPANY_FAILURE: "READ_COMPANY_FAILURE",
//     POST_COMPANY_START: "POST_COMPANY_START",
//     POST_COMPANY_SUCCESS: "POST_COMPANY_SUCCESS",
//     POST_COMPANY_FAILURE: "POST_COMPANY_FAILURE",
// };

// export default companyConstant;



export enum CompanyActionTypes {
    GET_COMPANIES_START = "GET_COMPANIES_START",
    GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS",
    GET_COMPANIES_FAILURE = "GET_COMPANIES_FAILURE",
    READ_COMPANY_START = "READ_COMPANY_START",
    READ_COMPANY_SUCCESS = "READ_COMPANY_SUCCESS",
    READ_COMPANY_FAILURE = "READ_COMPANY_FAILURE",
    POST_COMPANY_START = "POST_COMPANY_START",
    POST_COMPANY_SUCCESS = "POST_COMPANY_SUCCESS",
    POST_COMPANY_FAILURE = "POST_COMPANY_FAILURE",
};
  


