export const reportConstant = {
    GET_REPORTS_START: "GET_REPORTS_START",
    GET_REPORTS_SUCCESS: "GET_REPORTS_SUCCESS",
    GET_REPORTS_FAILURE: "GET_REPORTS_FAILURE",
    QUERY_REPORTS_START: "QUERY_REPORTS_START",
    QUERY_REPORTS_SUCCESS: "QUERY_REPORTS_SUCCESS",
    QUERY_REPORTS_FAILURE: "QUERY_REPORTS_FAILURE",
    POST_REPORT_START: "POST_REPORT_START",
    POST_REPORT_SUCCESS: "POST_REPORT_SUCCESS",
    POST_REPORT_FAILURE: "POST_REPORT_FAILURE",
};